version: '3.8'

services:
  blackcart:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_API_KEY=your_telegram_api_key
      - TELEGRAM_CHAT_ID=your_telegram_chat_id
      - TERM=xterm
      - GOTTY_USERNAME=blackcart
      - GOTTY_PASSWORD=blackcart
    volumes:
      - ./data:/work_dir/data  # Mount ./data from the host to /work_dir/data in the container

    # Use the following command if you want to enable the web terminal with HTTP and basic auth
    # command: ["sh", "-c", "gotty -w --credential $GOTTY_USERNAME:$GOTTY_PASSWORD /bin/bash"]

    # Use the following command if you want to enable TLS with basic auth
    command: ["sh", "-c", "gotty --tls --tls-crt /etc/gotty/cert.pem --tls-key /etc/gotty/key.pem -w --credential blackcart:blackcart /bin/bash"]
      
    # Uncomment the following line if you want the service to restart automatically
    # restart: unless-stopped
